<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CA1303;CA5394;CA1861;CA1848;CA1822;CA1859;CA1308;CA2000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" />
    <PackageReference Include="Emgu.CV.runtime.windows" />
  </ItemGroup>
</Project>
